### ISSUE TITLE
Implement all Tournament v4 endpoints

### ISSUE THREAD

**Issue by simivar** [simivar/riot-php#19]
Implement all Tournament v4 endpoints: [docs](https://developer.riotgames.com/apis#tournament-v4)

**Comment by Amoldreamer** [comment]
Hi simivar, would you clarify a bit more one the issue "Implement all Tournament v4 endpoints:".

**Comment by simivar** [comment]
Hey @Amoldreamer, sure! As you can see this library is in the early stages of its development and right now we only have two APIs covered: Third-Party Code and Summoner. The same way we have those two ready we need all others as well, that means:
- [ ] Creating `Tournament` class in `Riot\API\Version4` namespace
- [ ] Creating methods in `Tournament` class to send requests for every available endpoint from Riot API ([docs](https://developer.riotgames.com/apis#tournament-v4)) - so 6 new methods for this one - [example like methods in Summoner class](https://github.com/simivar/riot-php/blob/main/src/Riot/API/Version4/Summoner.php)
- [ ] Creating DTOs for methods from point 2 that return something more then scalar type & hydrate responses from API to those DTOs on return - [example on line 40 of Summoner class](https://github.com/simivar/riot-php/blob/main/src/Riot/API/Version4/Summoner.php#L40)
- [ ] Adding method to API Factory that returns the new API, exactly like `getSummonerV4Api` - [this is the factory](https://github.com/simivar/riot-php/blob/main/src/Riot/API.php#L22)

It seems pretty easy as it boils down to creating one API class and some DTOs. If you want to pick it up and/or something is not clear feel free to ask more questions. 

PS. How did you find this? Nice one as I just created it yestarday ;).

**Comment by simivar** [comment]
You can look at #20 and #21 for some examples.

**Comment by Amoldreamer** [comment]
Hey @simivar, I just made a search for PHP open source projects through advanced search and found this one. I am new here and I am trying open source projects for the first time. But I am surprised. Was my response too quick?
I went through your comments over and over again and I feel this is a bit complicated for me as I am still a beginner in PHP. I even don't know what's the right question to ask.

**Comment by Amoldreamer** [comment]
But please don't get me wrong. I am not saying I don't want to work on the project. It's just that I need to ask a lot of questions and some of the questions may be very basic.

**Comment by simivar** [comment]
Feel free to ask them, I can try to answer them & help you out. No, it wasn't too quick, I was just amazed that somebody found this library. 🥇

**Comment by Amoldreamer** [comment]
Ok, first of all, can you explain to me terms like 'v1',' v4', 'endpoints' and 'DTO'? And what does the website actually do?

**Comment by simivar** [comment]
So, in general, this library is a wrapper around Riot Games Developer APIs listed [here](https://developer.riotgames.com/apis). We want to make it easy for everyone to just install this library and get any data with any HTTP Client library from those APIs.

As you can see there are multiple **APIs**: ACCOUNT-V1, CHAMPION-MASTERY-V4, CHAMPION-V3, CLASH-V1, etc.

As you can see all of these APIs are suffixed with `-V1`, `-V3`, or `V4`. This is nothing more than **version** of the API. When Riot wants to do changes to data returned from API they introduce a new **version** and deprecate the one that is currently. So `-v1` means *version 1*. Thanks to that developers are informed when some breaking change happens and have time to switch from their old implementation to the new one. You can find more about Riot API Versioning [here](https://developer.riotgames.com/docs/portal#web-apis_versioning).

If you click on any of these APIs you will see a list of available HTTP routes to which you can send a request to get data - these are the **endpoints**. So, for *ACCOUNT-V1* API the first endpoint is */riot/account/v1/accounts/by-puuid/{puuid}*.

**DTO** is an architectural design pattern and means **Data Transfer Object**. To simplify things it is a class without any business logic that only storages data. It is used to transfer data between different applications (Riot API & our app) or different layers of the same application. It may contain serialization/deserialization methods (we have *createFromArray* method inside) but it's not required.

**Comment by Amoldreamer** [comment]
Hey @simivar, I had never heard about PHP wrappers. So it will take some time for me to learn about it. And I use Laravel as a framework.

**Comment by simivar** [comment]
This is a library. It's framework agnostic and does one job of communicating with Riot API. That's what I meant by *wrapper*. It could be called a *client* to communicate with the API.

**Comment by Amoldreamer** [comment]
Actually, I am trying to figure out what I don't know. There seems to be a lot of things that I do not know. Do I need to learn about php wrapper?

**Comment by simivar** [comment]
I've implemented the changes myself. You can look at #40 if you want to see what was meant to be done in this issue.
